# Generated by Django 4.1.7 on 2023-02-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjecteDjangoAlexMarcDavid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='data_de_creació',
            new_name='data_de_creacio',
        ),
    ]
