# Generated by Django 4.1.7 on 2023-02-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjecteDjangoAlexMarcDavid', '0002_rename_data_de_creació_platform_data_de_creacio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='nou',
            new_name='new',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='preu',
            new_name='price',
        ),
    ]
