version: '3.9'

services:
  web:
    image: devrrior/docker-django
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
